version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server 
    # ports:
    #   - "6379:6379"
    restart: always
    network_mode: host

  log4j-tester:
    depends_on:
      - redis
    build: .
    # ports:
    #   - "8001:8000"
    #   - "1389:1389"
    network_mode: host
# put CLI commands here to override defaults
    command: --hostname 0.0.0.0 --http-host 0.0.0.0 --http-port 8000 --ldap-host 0.0.0.0 --ldap-port 1389 --redis-url "redis://localhost:6379"